### PR TITLE
Fix DatabaseDefault crash in _update_days_seen. Closes #908

### LINKED ISSUE #908: Extraction error related to DatabaseDefault object
I got an error on one of my instances:

```
2026-02-28 14:00:15,378 - greedybear.cronjobs.extraction.pipeline.ExtractionPipeline - execute - ERROR - Extraction failed for honeypot Cowrie: 'DatabaseDefault' object has no attribute 'date'  
```

Presumed cause:
Since #887 we use `db_default=Now()` for `IOC.last_seen`,  This means that unsaved IOC instances have a `DatabaseDefault` object instead of an actual datetime. When `_update_days_seen()` calls `.date()` on it and crashes.

### PR DESCRIPTION
**Pull request by Sanchit2662**
## Summary
                                                                                                                                               
  This PR fixes the 'DatabaseDefault' object has no attribute 'date' error that crashes the extraction pipeline during Cowrie (and potentially
  other honeypot) processing. The issue was introduced after #887 switched IOC.last_seen from default=datetime.now to db_default=Now().

  With db_default, unsaved IOC instances no longer get a real datetime in memory — they get a DatabaseDefault sentinel instead. When
  _update_days_seen() tries to call .date() on that, it blows up.

  I traced this to three code paths where last_seen never gets explicitly set:
  - cowrie.py — payload hostname IOC creation
  - cowrie.py — download URL IOC creation
  - utils.py — iocs_from_hits() when hits lack timestamp fields (this one affects all honeypot strategies, not just Cowrie)

  ## Fix

  Rather than patching each of the three creation sites individually, I went with a chokepoint approach — every IOC flows through
  _update_days_seen() in ioc_processor.py regardless of which strategy created it, so guarding there covers all current and future cases in one
   place.

  - In _update_days_seen(), I added an isinstance check before calling .date(). If last_seen isn't a real datetime, it falls back to
  datetime.now().
  - In _merge_iocs(), I added a guard to skip overwriting existing.last_seen when the incoming IOC carries a DatabaseDefault. Without this, a  
  DatabaseDefault from a new unsaved IOC would silently corrupt a perfectly valid timestamp on an existing DB record.

Closes #908
 Based on the PR details provided, here are the checked items:

### Formalities

- [x] I have read and understood the rules about [how to Contribute](https://intelowlproject.github.io/docs/GreedyBear/Contribute/ ) to this project.
- [x] I chose an appropriate title for the pull request in the form: `<feature name>. Closes #999`
- [x] My branch is based on `develop`.
- [x] The pull request is for the branch `develop`.
- [x] I have reviewed and verified any LLM-generated code included in this PR.

## Docs and tests

- [x] I documented my code changes with docstrings and/or comments.
- [x] I have checked if my changes affect user-facing behavior that is described in the docs. If so, I also created a pull request in the docs repository.
- [x] Linter (Ruff) gave 0 errors. If you have correctly installed pre-commit, it does these checks and adjustments on your behalf.
- [ ] I have added tests for the feature/bug I solved.
- [ ] All the tests gave 0 errors.

## GUI changes

- [ ] I have provided a screenshot of the result in the PR.
- [ ] I have created new frontend tests for the new component or updated existing ones.

## Review process

- We encourage you to create a draft PR first, even when your changes are incomplete. This way you refine your code while we can track your progress and actively review and help.
- If you think your draft PR is ready to be reviewed by the maintainers, click the corresponding button. Your draft PR will become a real PR.
- If your changes decrease the overall tests coverage (you will know after the Codecov CI job is done), you should add the required tests to fix the problem.
- Every time you make changes to the PR and you think the work is done, you should explicitly ask for a review. After receiving a "change request", address the feedback and click "request re-review" next to the reviewer's profile picture at the top right.

### CODE REVIEW

**Comment by regulartim** [comment]
Hey @Sanchit2662 ! Where did the rest of the checklist from the PR template go?

**Comment by Sanchit2662** [comment]
Hey @regulartim, sorry about that  I accidentally removed part of the template while editing the description. I've added it back now. Let me know if anything else is missing!

**Comment by Sanchit2662** [comment]
That's a great point! Setting last_seen (and first_seen) from hit["timestamp"] in the two Cowrie constructors makes more sense , we'd get the actual event time instead of losing that information with a datetime.now() fallback. I'll update both IOC constructors in cowrie.py to pull from timestamp. I'll also keep the defensive isinstance check in _update_days_seen() as a safety net, in case any future code path introduces the same problem.

**Comment by Sanchit2662** [comment]
Hey @regulartim, I've pushed the update.

File: greedybear/cronjobs/extraction/ioc_processor.py
Comment (regulartim) [inline greedybear/cronjobs/extraction/ioc_processor.py:1]: I first thought we should leave your added guardrails here, but now I feel like removing them. If at this point `last_seen` is not a `datetime` object, something clearly went wrong and we should know about it. I think the code _should_ crash here to unmask bugs. 

Sorry, bu I would prefer if you completely remove your changes to this file.

Comment (Sanchit2662) [reply greedybear/cronjobs/extraction/ioc_processor.py:1]: @regulartim Done! Removed the guardrails from ioc_processor.py entirely.

**Review by regulartim — APPROVED** [review]
Nice! :)
